// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import AlignLeftOutlined from '/Users/liaoxinjian/Documents/学习/魔鬼训练营/interview-backstage/node_modules/@ant-design/icons/es/icons/AlignLeftOutlined';
export default { AlignLeftOutlined };
