// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/liaoxinjian/Documents/学习/魔鬼训练营/interview-backstage/src/models/global';
import model_2 from '/Users/liaoxinjian/Documents/学习/魔鬼训练营/interview-backstage/src/models/test';
import model_3 from '/Users/liaoxinjian/Documents/学习/魔鬼训练营/interview-backstage/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'global', model: model_1 },
model_2: { namespace: 'test', model: model_2 },
model_3: { namespace: '@@initialState', model: model_3 },
} as const
